### PR TITLE
fix(vyos): working vyos 1.5 template

### LINKED ISSUE #227: [BUG]VYOS image builder not working
### Description
The packer-build.sh script is not working, can't build a vyos.qc2 image.

### Checklist
- I have included no proprietary/sensitive information in my issue.

### PR DESCRIPTION
**Pull request by glattercj**
# VyOS template

## Description
New and working VyOS 1.5 template.

> [!WARNING]
> Requires the VyOS build script from https://github.com/sandialabs/sceptre-phenix-images/pull/13

## Related Issue
Resolves #227.

## Type of Change
Please select the type of change your pull request introduces:
- [X] Bugfix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please describe):

## Checklist
- [X] This PR conforms to the process detailed in the [Contributing Guide](https://github.com/sandialabs/sceptre-phenix/tree/main/.github/CONTRIBUTING.md).  
- [X] I have included no proprietary/sensitive information in my code. 
- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested my code.

## Additional Notes
The `hack/` directory and contents have been deleted, as the previous build scripts were updated and moved to the [images](https://github.com/sandialabs/sceptre-phenix-images/pull/13) repo.

Docs updated [here](https://github.com/sandialabs/sceptre-phenix-docs/pull/17).

Topos updated [here](https://github.com/sandialabs/sceptre-phenix-topologies/pull/15).

### CODE REVIEW

**Comment by cmulk** [comment]
> Wonder if this should be built in CI and pushed to ghcr like Clifton is doing in the images repo: [sandialabs/sceptre-phenix-images#12](https://github.com/sandialabs/sceptre-phenix-images/pull/12)

Yep I had that same thought, I like it! Probably would make sense to publish it in the sceptre-phenix-images repo as well even though it's a different/unique build process

**Comment by glattercj** [comment]
Moved and updated this PR with supporting template and injection location.

**Comment by glattercj** [comment]
> > Wonder if this should be built in CI and pushed to ghcr like Clifton is doing in the images repo: [sandialabs/sceptre-phenix-images#12](https://github.com/sandialabs/sceptre-phenix-images/pull/12)
> 
> Yep I had that same thought, I like it! Probably would make sense to publish it in the sceptre-phenix-images repo as well even though it's a different/unique build process

[Done](https://github.com/sandialabs/sceptre-phenix-images/pull/13)

**Review by GhostofGoes — APPROVED** [review]

**Comment by glattercj** [comment]
@GhostofGoes still draft because I need to add the following configurations to the template:

- [ ] firewall
- [ ] traffic-policy

**Comment by glattercj** [comment]
@GhostofGoes @activeshadow This is ready. I tested with the [wind scenario](https://github.com/sandialabs/sceptre-phenix-topologies/blob/main/renewables/wind/plant/phenix-configs/base/scenario.yml) that has a lot of vrouter action. Keep in mind this new template and code *will only work with VyOS 1.5*. I'm pushing an accompanying PR to sceptre-phenix-topologies shortly to match this new template.

File: src/go/app/vrouter.go [hunk 1]
```diff
@@ -55,19 +56,18 @@ type Emulator struct {
 	Egress     []string `mapstructure:"egress"`
 	Name       string   `mapstructure:"name"`
 	Bandwidth  string   `mapstructure:"bandwidth"`
-	Burst      string   `mapstructure:"burst"`
```
Comment (GhostofGoes) [inline src/go/app/vrouter.go:58]: Why was burst removed?

Comment (glattercj) [reply src/go/app/vrouter.go:58]: Because it's in [the official docs](https://docs.vyos.io/en/latest/configuration/trafficpolicy/index.html#cfgcmd-set-qos-policy-network-emulator-policy-name-burst-burst-size), but when you try to tab-complete it inside the running image, there's no `burst` option ¯\_(ツ)_/¯

**Comment by glattercj** [comment]
@activeshadow speak now or forever hold your peace

**Review by mgaliar — COMMENTED** [review]
LGTM!
